version: '3.4'

services:
  mongodb:
    image: mongo
    networks:
      - todo
    ports:
      - 27017:27017

  mongodb-seed:
    build: ./test/seed
    networks:
      - todo
    depends_on:
      - mongodb

  test:
    build:
      context: .
      target: test
    container_name: todo-api-test
    networks:
      - todo
    environment:
      - NODE_ENV=test
      - PORT=3000
      - TODO_MONGODB_CONNECTION_STRING=mongodb://mongodb/case
    depends_on:
      - mongodb
      - mongodb-seed

  production:
    build: .
    container_name: todo-api-production
    ports:
      - 3000:3000
    networks:
      - todo
    environment:
      - NODE_ENV=production
      - PORT=3000
      - TODO_MONGODB_CONNECTION_STRING=mongodb://mongodb/case
    depends_on:
      - mongodb
      - mongodb-seed

networks:
  todo:
    driver: bridge
