name: todo-api-pr

on:
  pull_request:
    branches:
      - main
    paths:
      - "api/*"
      - "api/**"

defaults:
  run:
    working-directory: api

jobs:
  pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install dependencies
        run: yarn install

      - name: Run eslint
        run: yarn lint

      - name: Run tests
        run: docker-compose run test
