name: todo-api-deployment

on:
  push:
    branches:
      - main
    paths:
      - "api/*"
      - "api/**"

defaults:
  run:
    working-directory: api

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Google Cloud CLI
        uses: google-github-actions/setup-gcloud@master
        with:
          version: "290.0.1"
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_KEYFILE }}

      - name: Build docker image and push it to Google Container Registry
        run: gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/todo-app

      - name: Deploy image to cloud run
        run: gcloud run deploy todo-app --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/todo-app --platform managed --region ${{ secrets.GCP_REGION }} --set-env-vars NODE_ENV=${{ secrets.NODE_ENV }} --set-env-vars TODO_MONGODB_CONNECTION_STRING=${{ secrets.TODO_MONGODB_CONNECTION_STRING }}
